apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-company-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: companies-company-service
  template:
    metadata:
      labels:
        app: companies-company-service
    spec:
      initContainers:
        - name: db-init
          {{- include "backend-library.db-init" . | nindent 10 }}
      containers:
        - name: companies-company-service
          image: borismakhlin/company-service:0.0.1
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Values.db.host }}:{{ default 5432 .Values.db.port }}/{{ .Values.db.name }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.db.user.name }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.db.user.password }}