apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-company-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: companies-company-service
  template:
    metadata:
      labels:
        app: companies-company-service
    spec:
      containers:
        - name: companies-company-service
          image: borismakhlin/company-service:0.0.1
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://app-companies-postgres:5432/company
            - name: SPRING_DATASOURCE_USERNAME
              value: company
            - name: SPRING_DATASOURCE_PASSWORD
              value: companypass