apiVersion: v1
kind: Service
metadata:
  name: companies-company-service
spec:
  selector:
    app: companies-company-service
  ports:
    - name: http
      port: 80
      targetPort: 5010
      nodePort: 30002
  type: NodePort