/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.46).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.makhlin.companyservice.swagger.api;

import com.makhlin.companyservice.swagger.model.BusinessConfiguration;
import com.makhlin.companyservice.swagger.model.ErrorResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


@Validated
public interface ConfigurationApi {

    ConfigurationApiDelegate getDelegate();

    @Operation(summary = "Get configuration.", description = "Returns business configuration", tags = {"CONFIGURATION"})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = BusinessConfiguration.class))),

            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class)))})
    @RequestMapping(value = "/v1/companies/configuration",
            produces = {"application/json"},
            method = RequestMethod.GET)
    default ResponseEntity<BusinessConfiguration> getConfiguration() {
        return getDelegate().getConfiguration();
    }

}

