apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: companies-analytics-service
  template:
    metadata:
      labels:
        app: companies-analytics-service
    spec:
      initContainers:
        - name: db-init
          {{- include "analytics-db-init" . | nindent 10 }}
      containers:
        - name: companies-analytics-service
          image: borismakhlin/analytics-service:0.0.1
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://app-companies-postgres:5432/analytics
            - name: SPRING_DATASOURCE_USERNAME
              value: analytics
            - name: SPRING_DATASOURCE_PASSWORD
              value: analyticspass