apiVersion: v1
kind: Service
metadata:
  name: companies-analytics-service
spec:
  selector:
    app: companies-analytics-service
  ports:
    - name: http
      port: 80
      targetPort: 5020
      nodePort: 30001
  type: NodePort